import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Nav from "../components/Nav";
import Portada from "../components/Portada";
import Numeros from "../components/Numeros";
import Modal from "../components/Modal";
import { useState } from "react";
import Testimonial from "../components/Testimonial";
import Carrusel from "../components/Carrusel";
import Carrusel2 from "../components/Carrusel2";
import Footer from "../components/Footer";
import CarrsuselSkeletor from "../components/CarrsuselSkeletor";
import Clientes from "../components/Clientes";
import Fondo from "../components/Fondo";

export default function Home() {
  const mover = () => {
    console.log("moviendo");
  };
  return (
    <>
      <Head>
        <title>Actitud Digital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <Portada />
        <div className="serviciosHome z-50 bg-black relative pt-24  "></div>
        <Image
          src="/img/wave.svg"
          width={1200}
          height={500}
          className="w-full bg-white relative waveDesktop"
        />

        <Carrusel />
        <div className="flex justify-center gap-4 fraseDesktop relative bg-white py-44 -mt-[200px] h-screen fondoAnimado3">
          <div className="w-full  ">
            <h2 className="text-center text-[#1C4ED8] relative font-extrabold text-8xl mt-12 mb-32 swirl-in-fwd">
              "Lo que no podemos medir <br></br>{" "}
              <span className="text-white bg-[#1C4ED8] relative top-6">
                no podemos mejorar"
              </span>
            </h2>
          </div>
        </div>
        <Image
          src="/img/wave.svg"
          width={1200}
          height={500}
          className="w-[100%] bg-white relative -mt-20 mb-5 pb-[162px] h-[40vh] waveMobile"
        />
        <div className="flex justify-center gap-4 fraseMobile relative bg-white py-44 -mt-[200px] h-[50vh] fondoAnimado3">
          <div className="w-[95%] mx-auto ">
            <h2 className="text-center text-[#1C4ED8] relative font-extrabold text-4xl -mt-20 mb-32 swirl-in-fwd">
              "Lo que no podemos medir <br></br>{" "}
              <span className="text-white bg-[#1C4ED8] relative top-0">
                no podemos mejorar"
              </span>
            </h2>
          </div>
        </div>
        <div className=" relative bg-white hover:bg-black  hover:text-white transition-colors">
          <h2 className="text-center  font-extrabold text-5xl pt-24 ">
            Clientes
          </h2>
          {/* <Carrusel2 /> */}
          <Clientes />
        </div>
      </main>
      <Footer />
    </>
  );
}
